// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemSchoolV1.Infrastructure.Kelas;

#nullable disable

namespace SystemSchoolV1.Api.Migrations
{
    [DbContext(typeof(KelasDbContext))]
    partial class KelasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemSchoolV1.Domain.Entities.KelasModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JamBuka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JamTutup")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamaKelas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KelasModels");
                });
#pragma warning restore 612, 618
        }
    }
}
